name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.12, ]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --deploy --dev

      - name: Initialize .env
        run: cp .env.example .env

      # If we ever need to use secret manager for the .env file:
      #      - id: 'auth'
      #        uses: 'google-github-actions/auth@v2'
      #        with:
      #          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/indabom'
      #          service_account: '${{ vars.GCP_SERVICE_ACCOUNT }}'
      #
      #      - id: 'secrets'
      #        uses: 'google-github-actions/get-secretmanager-secrets@v2'
      #        with:
      #          secrets: |-
      #            ENV_CONTENTS:projects/${{ vars.GCP_PROJECT_ID }}/secrets/django_settings_cicd/versions/latest
      #
      #      - name: Create .env file
      #        run: |
      #          echo "${{ steps.secrets.outputs.ENV_CONTENTS }}" > .env

      - name: Run Tests
        run: |
          pipenv run python manage.py test
